### ISSUE TITLE
List of common use cases to document

### ISSUE THREAD

**Issue by nickdickinson** [bedatadriven/activityinfo-R#122]
What are common use cases that we could document?

- From customer success team
- From existing batch scripts commonly used
- Existing tutorial that may need updates

Let's use this issue to track these for the next release.

**Comment by nickdickinson** [comment]
Use cases from existing issues and features. Shall we include this in the work?:
- [ ] Getting records from nested forms / references etc. (from milestone 4.37 issues)
- [ ] Updating / importing reference fields #129 #92 - really an example of creating a new form programmatically with sub-forms and reference fields and loading data could do this.
- [ ] Moving forms and creating folders #121 
- [ ] Creating roles for a team #133 
- [ ] Get metadata about the content of roles, forms, and databases in a tidy tibble/table format #39
- [ ] Get billing and database metadata #26
- [ ] List all users and roles and resources #26
- [ ] Adding / updating attachments #135

**Comment by jamiewhths** [comment]
@nickdickinson sent you a file via email from CS which covers some of the most common use cases in an early form of documentation which could be expanded out.

**Comment by jamiewhths** [comment]
Order of priority:
- [ ]  Creating roles for a team https://github.com/bedatadriven/activityinfo-R/issues/133
- [ ] Processing examples from CS into tutorials/how-tos
- [ ]  Adding / updating attachments https://github.com/bedatadriven/activityinfo-R/issues/135
---
- [ ] Getting records from nested forms / references etc. (from milestone 4.37 issues)
- [ ]  Updating / importing reference fields https://github.com/bedatadriven/activityinfo-R/issues/129 https://github.com/bedatadriven/activityinfo-R/issues/92 - really an example of creating a new form programmatically with sub-forms and reference fields and loading data could do this.
- [ ]  Moving forms and creating folders https://github.com/bedatadriven/activityinfo-R/issues/121
- [ ]  Get metadata about the content of roles, forms, and databases in a tidy tibble/table format https://github.com/bedatadriven/activityinfo-R/issues/39
- [ ]  Get billing and database metadata https://github.com/bedatadriven/activityinfo-R/issues/26
- [ ]  List all users and roles and resources https://github.com/bedatadriven/activityinfo-R/issues/26

**Comment by Ryo-N7** [comment]
a few more examples:

- **get database roles function:**
```R
getDatabaseRoles <- function(databaseId) {
  # vimplusdbid <- "c9r36oole40p8ex2j30"
  databaseTree <- getDatabaseTree(databaseId)

  dbrolesdf <- dplyr::tibble(
    id = unlist(lapply(databaseTree$roles, function(x) {x$id})),
    label = unlist(lapply(databaseTree$roles, function(x) {x$label})),
    permissions = lapply(databaseTree$roles, function(x) {x$permissions}),
    parameters = lapply(databaseTree$roles, function(x) {x$parameters}),
    filters = lapply(databaseTree$roles, function(x) {x$filters}),
    grants = lapply(databaseTree$roles, function(x) {x$grants}),
    version = unlist(lapply(databaseTree$roles, function(x) {x$version})),
    grantBased = unlist(lapply(databaseTree$roles, function(x) {x$grantBased}))
  )

  return(dbrolesdf)
}
```

- **search for resource across ALL databases on account based on resource ID (can modify to use resource label, etc...):**
```R
getdbrecs_df <- function(dbid, dblabel) {
  dbrecdf <- activityinfo::getDatabaseResources(dbid) %>%
    dplyr::mutate(
      databaseId = dbid,
      dblabel = dblabel) %>%
    dplyr::rename(resourceId = id, resourceLabel = label)

  return(dbrecdf)
}

search_resource_activityinfo <- function(resourceId) {

  alldbsdf <- activityinfo::getDatabases() %>% dplyr::select(databaseId, label)
  alldb_ids <- alldbsdf$databaseId
  alldb_labels <- alldbsdf$label

  alldbrecs <- purrr::map2(alldb_ids, alldb_labels, ~ getdbrecs_df(.x, .y))

  alldbrecs_df <- purrr::reduce(alldbrecs, bind_rows)

  if (is.na(resourceId)) {
    return(alldbrecs_df)
  } else {
    dbrec_filtered <- alldbrecs_df %>% dplyr::filter(resourceId == resourceId)
    return(dbrec_filtered)
  }
}
```

- get all 'Inactive' roles from databases

```R
alldbs <- getDatabases()

get_all_inactive_ids <- function(databaseId) {
  ## search db schema for role info
  dbschm <- getDatabaseTree(databaseId)
  
  dbroles <- dbschm[["roles"]]
  
  ## the ID for "Inactive" role
  inactiveid <- dbroles %>% 
    keep(~ .x$label == "Inactive") %>% 
    map_chr(~ .x$id)
  
  inactdf <- data.frame("db_id" = databaseId,
                        "inactive_id" = inactiveid)
  
  return(inactdf)
}

safe_get_all_inactive_ids <- purrr::safely(get_all_inactive_ids)

allinactids_output <- map(alldbsclean$databaseId, 
                      ~ safe_get_all_inactive_ids(databaseId = .x))

allinactids_df <- allinactids_output %>% 
  map("result") %>% 
  discard(is.null) %>% 
  reduce(bind_rows)
```

- **find all forms in database with 'public' visibility setting:**

```R
PrList <- getDatabases()

get_public_visibles <- function(dblabel, dbid) {
  cat(paste0("\n\nDatabase: ", dblabel, "\n\n"))
  dbrecs <- getDatabaseResources(dbid)
  dbrecs <- dbrecs %>% 
    filter(visibility == "PUBLIC", type == "FORM") %>% 
    mutate(project = dblabel,
           url = AVDGconvenience::getActivityInfoURL(formId = id)) %>% 
    select(project, id, label, visibility, url)
  cat(paste0("\n\nDatabase: ", dblabel, "... Done!\n\n"))
  return(dbrecs)
}

allpubvisdf <- map2_dfr(PrList$label, PrList$databaseId, ~ get_public_visibles(dblabel = .x, dbid = .y))
```
