### ISSUE TITLE
final checklist for Enhancement project

### ISSUE THREAD

**Issue by Ryo-N7** [bedatadriven/activityinfo-R#76]
**Absolute must-haves before project finish:**

- [x] (Alex) Fix importer size limit issue (add extra argument for GCP)
- [x] (Alex) `addRecord()` should fail if record already exists, see https://github.com/bedatadriven/activityinfo-R/issues/43
- [ ] (Alex) Exposed meta-data for forms/databases for meta-analysis and insights, see https://github.com/bedatadriven/activityinfo-R/issues/39
- [x] (Nick) Get records as exactly as it appears in User Interface (I can type in column names as they appear in UI into `queryTable()` and I'll get those columns even if they are references to other tables)
- [x] (Nick) Form schema constructor based on data.frame/Excel/csv  input
- [x] (Nick) `migrateField()`: to be able to change data type of a column and push data into the new column from the old one in a form/table, also this bug(?): https://github.com/bedatadriven/activityinfo-R/issues/82
- [x] (Alex) **Documentation**: 
     - re-write vignettes + examples in (https://github.com/bedatadriven/activityinfo-R/tree/master/inst/examples):
     - "`grants/roles/permissions` with {activityinfo} R functions"
     - documentation on dot notation in formulas for JOINS in R functions (and just for use in ActivityInfo in general...),,,, 
     - (Nick) add `createFormSchemaFromData()` function to existing add/manipulate forms vignette: https://www.activityinfo.org/support/docs/R/tutorials/add-and-manipulate-forms.html, see https://github.com/bedatadriven/activityinfo-R/issues/74
- [x] (Alex?) set Nic & Ryo as authors/contributors to package DESCRIPTION, also cite ACDI/VOCA as funding contributors?? -- need to do some research on how to stipulate this in DESCRIPTION file... >> maybe README instead?
- [x] `importTable/Records()` server error: https://github.com/bedatadriven/activityinfo-R/issues/81

---------------------------------

**Nice-to-haves before project finish**:

- [x] (Nick/Ryo) `getRecordHistory()` output in data.frame format: https://github.com/bedatadriven/activityinfo-R/issues/57
- [ ] more investigation + discussion on return output (esp now that lots of new functions have been created): https://github.com/orgs/bedatadriven/projects/1/views/1?pane=issue&itemId=16326444
- [x] (Nick/Ryo/Alex): convert output of `getDatabaseUsers()` into a nice data.frame format

**Comment by nickdickinson** [comment]
FYI there is some weirdness with the S3 methods where I had to explicitly reexport filter from dplyr to get it to work. Perhaps because of the fact that dplyr already masks filter from stats with dplyr::filter

**Comment by Ryo-N7** [comment]
for converting `getDatabaseUsers()` into a data.frame it's pretty easy to just do:
```
as.data.frame(do.call(rbind, db_user_list_object))
```

i can push that into the v4.33 branch as well if it's OK? might break some people's code potentially though if they've been doing that themselves which is pretty likely

**Comment by nickdickinson** [comment]
Looks ok to me. But perhaps use an asDf = TRUE argument default to enable some users to turn it off like with getDatabases()?

**Comment by nickdickinson** [comment]
@Ryo-N7 @akbertram I believe I have completed my tasks. I've pushed the last version. @akbertram will push also some new documentation before release. Looking forward to the release!

**Comment by Ryo-N7** [comment]
based on this: https://journal.r-project.org/archive/2012-1/RJournal_2012-1_Hornik~et~al.pdf

I edited the "authors" section of the DESCRIPTION file.
```
Authors@R: c(
    person("Alex", "Bertram", email = "alex@bedatadriven.com", 
           role = c("aut", "cre")),
    person("Nicolas", "Dickinson", email = "dickinson@washnote.com", 
           role = "aut"),
    person("Ryo", "Nakagawara", email = "rnakagawara@acdivoca-aux.org", 
           role = "ctb"),
    person("BeDataDriven B.V.", role = c("cph", "fnd"))
  )
```

also wanted to update the title + description text:
Title: `Title: Query and update datasets from ActivityInfo.org`
Description: `Description: An interface to ActivityInfo, an information management system.`

to...
Title: `R interface to ActivityInfo.org, an Information management software for
    humanitarian and development operations.`
Description: `An interface to ActivityInfo, a web-based information management software 
    used for partner reporting, monitoring and evaluation and case management in
    humanitarian aid, emergencies and international development.`

I took text for both from the main website. What do you think @akbertram ? If you're OK with this, I can push it to the branch.

**Comment by Ryo-N7** [comment]
there's one (?) function in the package that use the base R pipe `|>`. many people (including me!) don't have R `4.1` yet so it might need to be tweaked or at the very least there should be a warning in the package docs or specified in the DESCRIPTION.

anyway, I see that `v4.33` branch is already merged so as I do more UAT for the next week, i'll branch off to `4.33.9999` or something as I have...

- some typos I've found in the docs
- the DESCRIPTION file changes as noted in previous comment
- etc.

**Comment by Ryo-N7** [comment]
(Alex) addRecord() should fail if record already exists, see https://github.com/bedatadriven/activityinfo-R/issues/43 

will be done soon by alex, hopefully by end of this week
